info:
  app:
    name: "spring-cloud-dataflow-server"
    description: "Spring Cloud Data Flow Server"
    version: "2.11.5"
spring:
  cloud:
    dataflow:
      version-info:
        dependency-fetch:
          enabled: false
        dependencies:
          spring-cloud-dataflow-server:
            name: Spring Cloud Dataflow
            version: "2.11.5"
          spring-cloud-dataflow-dashboard:
            name: Spring Cloud Dataflow UI
            version: "3.4.6"
          spring-cloud-dataflow-core:
            name: Spring Cloud Data Flow Core
            version: "2.11.5"
          spring-cloud-dataflow-implementation:
            name: ${info.app.name}
            version: "2.11.5"
          spring-cloud-dataflow-shell:
            name: Spring Cloud Data Flow Shell
            version: "2.11.5"
            url: "{repository}/org/springframework/cloud/spring-cloud-dataflow-shell/{version}/spring-cloud-dataflow-shell-{version}.jar"
            checksum-sha1-url: "{repository}/org/springframework/cloud/spring-cloud-dataflow-shell/{version}/spring-cloud-dataflow-shell-{version}.jar.sha1"
            checksum-sha256-url: "{repository}/org/springframework/cloud/spring-cloud-dataflow-shell/{version}/spring-cloud-dataflow-shell-{version}.jar.sha256"
  jpa:
    hibernate:
      ddl-auto: none